### ISSUE TITLE
Differencing to make data stationary

### ISSUE THREAD

**Issue by bigfivecode** [Idilismiguzel/Time-Series#1]
The code in notebook shows that differencing was used to make the data stationary however doesn't the prediction portion of the code use the original dataframe prior to differencing?

**Comment by Idilismiguzel** [comment]
Hi, Thanks for the comment! In the code, I did the differentiation with **d=1** in the pm.auto_arima and in SARIMAX with order=(1,1,0) where order means (p, d, q). The parameter **d** stands for the differencing order. In the code, I was demonstrating with df_diff = df.diff().diff(12) before adfuller test to decide whether differencing 1 time is enough to make the data stationary. Since it was enough, in the prediction part I applied this with d=1 parameter and D=12 due to seasonality. You can also see the article I've written on this code here: https://towardsdatascience.com/hands-on-time-series-forecasting-with-python-d4cdcabf8aac. 
I hope this answer clarifies your doubt!!

**Comment by bigfivecode** [comment]
> Hi, Thanks for the comment! In the code, I did the differentiation with **d=1** in the pm.auto_arima and in SARIMAX with order=(1,1,0) where order means (p, d, q). The parameter **d** stands for the differencing order. In the code, I was demonstrating with df_diff = df.diff().diff(12) before adfuller test to decide whether differencing 1 time is enough to make the data stationary. Since it was enough, in the prediction part I applied this with d=1 parameter and D=12 due to seasonality. You can also see the article I've written on this code here: https://towardsdatascience.com/hands-on-time-series-forecasting-with-python-d4cdcabf8aac.
> I hope this answer clarifies your doubt!!

Great thanks for clarifying
